name: UHC_rebirth
version: '${project.version}'
main: com.vch.uhc_rebirth.UHC_rebirth
api-version: '1.20'
authors: [VCH]
description: Minecraft Ultra Hardcore Plugin

commands:
  reset-health:
    description: "Reset current health to 20HP"

